//*********************************************************************************************************************
//  Description: application identification between router agents and SDK service manager
//
//  Copyright (c) 2018 Nokia
//*********************************************************************************************************************

// NDK Version: v0.4.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: ndk/appid_service.proto

package ndk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Represents appid subscription request.
type AppIdentSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *AppIdentKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // Optional, to filter on name
}

func (x *AppIdentSubscriptionRequest) Reset() {
	*x = AppIdentSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_appid_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppIdentSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIdentSubscriptionRequest) ProtoMessage() {}

func (x *AppIdentSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_appid_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIdentSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*AppIdentSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_ndk_appid_service_proto_rawDescGZIP(), []int{0}
}

func (x *AppIdentSubscriptionRequest) GetKey() *AppIdentKey {
	if x != nil {
		return x.Key
	}
	return nil
}

// *
//
//	Represents appid key.
type AppIdentKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Application id
}

func (x *AppIdentKey) Reset() {
	*x = AppIdentKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_appid_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppIdentKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIdentKey) ProtoMessage() {}

func (x *AppIdentKey) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_appid_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIdentKey.ProtoReflect.Descriptor instead.
func (*AppIdentKey) Descriptor() ([]byte, []int) {
	return file_ndk_appid_service_proto_rawDescGZIP(), []int{1}
}

func (x *AppIdentKey) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// *
// Represents appid data.
type AppIdentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // Application name
	Author      string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`                               // Author name
	IsConnected bool   `protobuf:"varint,3,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"` // Connected to IDB or not
	Version     string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                             // Version string
}

func (x *AppIdentData) Reset() {
	*x = AppIdentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_appid_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppIdentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIdentData) ProtoMessage() {}

func (x *AppIdentData) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_appid_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIdentData.ProtoReflect.Descriptor instead.
func (*AppIdentData) Descriptor() ([]byte, []int) {
	return file_ndk_appid_service_proto_rawDescGZIP(), []int{2}
}

func (x *AppIdentData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppIdentData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AppIdentData) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *AppIdentData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// *
// Represents appid notification.
type AppIdentNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   SdkMgrOperation `protobuf:"varint,1,opt,name=op,proto3,enum=srlinux.sdk.SdkMgrOperation" json:"op,omitempty"` // Operation such as create, delete, or update
	Key  *AppIdentKey    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                 // AppIdent key
	Data *AppIdentData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                               // AppIdent data
}

func (x *AppIdentNotification) Reset() {
	*x = AppIdentNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_appid_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppIdentNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIdentNotification) ProtoMessage() {}

func (x *AppIdentNotification) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_appid_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIdentNotification.ProtoReflect.Descriptor instead.
func (*AppIdentNotification) Descriptor() ([]byte, []int) {
	return file_ndk_appid_service_proto_rawDescGZIP(), []int{3}
}

func (x *AppIdentNotification) GetOp() SdkMgrOperation {
	if x != nil {
		return x.Op
	}
	return SdkMgrOperation_Create
}

func (x *AppIdentNotification) GetKey() *AppIdentKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AppIdentNotification) GetData() *AppIdentData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ndk_appid_service_proto protoreflect.FileDescriptor

var file_ndk_appid_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x64, 0x6b, 0x2f, 0x61, 0x70, 0x70, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x72, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x1a, 0x14, 0x6e, 0x64, 0x6b, 0x2f, 0x73, 0x64, 0x6b, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x1b,
	0x41, 0x70, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x4b,
	0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1d, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x77, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x9f, 0x01, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x53, 0x64, 0x6b, 0x4d, 0x67, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x2a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x6f, 0x6b, 0x69, 0x61, 0x2f, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2d, 0x6e, 0x64,
	0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x6e, 0x64, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ndk_appid_service_proto_rawDescOnce sync.Once
	file_ndk_appid_service_proto_rawDescData = file_ndk_appid_service_proto_rawDesc
)

func file_ndk_appid_service_proto_rawDescGZIP() []byte {
	file_ndk_appid_service_proto_rawDescOnce.Do(func() {
		file_ndk_appid_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ndk_appid_service_proto_rawDescData)
	})
	return file_ndk_appid_service_proto_rawDescData
}

var file_ndk_appid_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ndk_appid_service_proto_goTypes = []interface{}{
	(*AppIdentSubscriptionRequest)(nil), // 0: srlinux.sdk.AppIdentSubscriptionRequest
	(*AppIdentKey)(nil),                 // 1: srlinux.sdk.AppIdentKey
	(*AppIdentData)(nil),                // 2: srlinux.sdk.AppIdentData
	(*AppIdentNotification)(nil),        // 3: srlinux.sdk.AppIdentNotification
	(SdkMgrOperation)(0),                // 4: srlinux.sdk.SdkMgrOperation
}
var file_ndk_appid_service_proto_depIdxs = []int32{
	1, // 0: srlinux.sdk.AppIdentSubscriptionRequest.key:type_name -> srlinux.sdk.AppIdentKey
	4, // 1: srlinux.sdk.AppIdentNotification.op:type_name -> srlinux.sdk.SdkMgrOperation
	1, // 2: srlinux.sdk.AppIdentNotification.key:type_name -> srlinux.sdk.AppIdentKey
	2, // 3: srlinux.sdk.AppIdentNotification.data:type_name -> srlinux.sdk.AppIdentData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ndk_appid_service_proto_init() }
func file_ndk_appid_service_proto_init() {
	if File_ndk_appid_service_proto != nil {
		return
	}
	file_ndk_sdk_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ndk_appid_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppIdentSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_appid_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppIdentKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_appid_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppIdentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_appid_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppIdentNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ndk_appid_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ndk_appid_service_proto_goTypes,
		DependencyIndexes: file_ndk_appid_service_proto_depIdxs,
		MessageInfos:      file_ndk_appid_service_proto_msgTypes,
	}.Build()
	File_ndk_appid_service_proto = out.File
	file_ndk_appid_service_proto_rawDesc = nil
	file_ndk_appid_service_proto_goTypes = nil
	file_ndk_appid_service_proto_depIdxs = nil
}
