//*********************************************************************************************************************
//  Description: interface between router agents and SDK service manager
//
//  Copyright (c) 2018 Nokia
//*********************************************************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: ndk/bfd_service.proto

package ndk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Represents BFD session status.
type BfdmgrSessionStatus int32

const (
	BfdmgrSessionStatus_INVALID    BfdmgrSessionStatus = 0 // Session invalid
	BfdmgrSessionStatus_ADMIN_DOWN BfdmgrSessionStatus = 1 // Admin down
	BfdmgrSessionStatus_DOWN       BfdmgrSessionStatus = 2 // Status down
	BfdmgrSessionStatus_INIT       BfdmgrSessionStatus = 3 // Status initializing
	BfdmgrSessionStatus_UP         BfdmgrSessionStatus = 4 // Status up and running
)

// Enum value maps for BfdmgrSessionStatus.
var (
	BfdmgrSessionStatus_name = map[int32]string{
		0: "INVALID",
		1: "ADMIN_DOWN",
		2: "DOWN",
		3: "INIT",
		4: "UP",
	}
	BfdmgrSessionStatus_value = map[string]int32{
		"INVALID":    0,
		"ADMIN_DOWN": 1,
		"DOWN":       2,
		"INIT":       3,
		"UP":         4,
	}
)

func (x BfdmgrSessionStatus) Enum() *BfdmgrSessionStatus {
	p := new(BfdmgrSessionStatus)
	*p = x
	return p
}

func (x BfdmgrSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BfdmgrSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ndk_bfd_service_proto_enumTypes[0].Descriptor()
}

func (BfdmgrSessionStatus) Type() protoreflect.EnumType {
	return &file_ndk_bfd_service_proto_enumTypes[0]
}

func (x BfdmgrSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BfdmgrSessionStatus.Descriptor instead.
func (BfdmgrSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{0}
}

// / Represents BFD session type.
type BfdmgrSessionType int32

const (
	BfdmgrSessionType_SESSION_TYPE_UNKNOWN   BfdmgrSessionType = 0 // Unknown session type
	BfdmgrSessionType_SESSION_TYPE_P2P       BfdmgrSessionType = 1 // Peer-to-peer session type
	BfdmgrSessionType_SESSION_TYPE_MICROBFD  BfdmgrSessionType = 2 // microbfd session type
	BfdmgrSessionType_SESSION_TYPE_SBFD_ECHO BfdmgrSessionType = 3 // seamless BFD session type, echo initiator
)

// Enum value maps for BfdmgrSessionType.
var (
	BfdmgrSessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNKNOWN",
		1: "SESSION_TYPE_P2P",
		2: "SESSION_TYPE_MICROBFD",
		3: "SESSION_TYPE_SBFD_ECHO",
	}
	BfdmgrSessionType_value = map[string]int32{
		"SESSION_TYPE_UNKNOWN":   0,
		"SESSION_TYPE_P2P":       1,
		"SESSION_TYPE_MICROBFD":  2,
		"SESSION_TYPE_SBFD_ECHO": 3,
	}
)

func (x BfdmgrSessionType) Enum() *BfdmgrSessionType {
	p := new(BfdmgrSessionType)
	*p = x
	return p
}

func (x BfdmgrSessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BfdmgrSessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ndk_bfd_service_proto_enumTypes[1].Descriptor()
}

func (BfdmgrSessionType) Type() protoreflect.EnumType {
	return &file_ndk_bfd_service_proto_enumTypes[1]
}

func (x BfdmgrSessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BfdmgrSessionType.Descriptor instead.
func (BfdmgrSessionType) EnumDescriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{1}
}

// / Represents BFD session subtype.
type BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType int32

const (
	BfdmgrGeneralSessionDataPb_SESSION_SUB_TYPE_UNKNOWN    BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType = 0 // Session subtype unknown
	BfdmgrGeneralSessionDataPb_SESSION_SUB_TYPE_SINGLE_HOP BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType = 1 // Single-hop session
	BfdmgrGeneralSessionDataPb_SESSION_SUB_TYPE_MULTI_HOP  BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType = 2 // Multi-hop session
	BfdmgrGeneralSessionDataPb_SESSION_SUB_TYPE_MICROBFD   BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType = 3 // microbfd session
	BfdmgrGeneralSessionDataPb_SESSION_SUB_TYPE_SBFD_ECHO  BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType = 4 // microbfd session
)

// Enum value maps for BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType.
var (
	BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType_name = map[int32]string{
		0: "SESSION_SUB_TYPE_UNKNOWN",
		1: "SESSION_SUB_TYPE_SINGLE_HOP",
		2: "SESSION_SUB_TYPE_MULTI_HOP",
		3: "SESSION_SUB_TYPE_MICROBFD",
		4: "SESSION_SUB_TYPE_SBFD_ECHO",
	}
	BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType_value = map[string]int32{
		"SESSION_SUB_TYPE_UNKNOWN":    0,
		"SESSION_SUB_TYPE_SINGLE_HOP": 1,
		"SESSION_SUB_TYPE_MULTI_HOP":  2,
		"SESSION_SUB_TYPE_MICROBFD":   3,
		"SESSION_SUB_TYPE_SBFD_ECHO":  4,
	}
)

func (x BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType) Enum() *BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType {
	p := new(BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType)
	*p = x
	return p
}

func (x BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType) Descriptor() protoreflect.EnumDescriptor {
	return file_ndk_bfd_service_proto_enumTypes[2].Descriptor()
}

func (BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType) Type() protoreflect.EnumType {
	return &file_ndk_bfd_service_proto_enumTypes[2]
}

func (x BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType.Descriptor instead.
func (BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType) EnumDescriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{2, 0}
}

// *
// Represents BFD session subscription request.
type BfdSessionSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *BfdmgrGeneralSessionKeyPb `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // Optional, to filter on name
}

func (x *BfdSessionSubscriptionRequest) Reset() {
	*x = BfdSessionSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdSessionSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdSessionSubscriptionRequest) ProtoMessage() {}

func (x *BfdSessionSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdSessionSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*BfdSessionSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{0}
}

func (x *BfdSessionSubscriptionRequest) GetKey() *BfdmgrGeneralSessionKeyPb {
	if x != nil {
		return x.Key
	}
	return nil
}

// *
// Represents BFD session key.
type BfdmgrGeneralSessionKeyPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is always present, other key field presence is determined by type
	Type BfdmgrSessionType `protobuf:"varint,10,opt,name=type,proto3,enum=srlinux.sdk.BfdmgrSessionType" json:"type,omitempty"` // Session type
	// Types that are assignable to Key:
	//
	//	*BfdmgrGeneralSessionKeyPb_P2P
	//	*BfdmgrGeneralSessionKeyPb_Microbfd
	//	*BfdmgrGeneralSessionKeyPb_Sbfdecho
	Key isBfdmgrGeneralSessionKeyPb_Key `protobuf_oneof:"Key"`
}

func (x *BfdmgrGeneralSessionKeyPb) Reset() {
	*x = BfdmgrGeneralSessionKeyPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdmgrGeneralSessionKeyPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdmgrGeneralSessionKeyPb) ProtoMessage() {}

func (x *BfdmgrGeneralSessionKeyPb) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdmgrGeneralSessionKeyPb.ProtoReflect.Descriptor instead.
func (*BfdmgrGeneralSessionKeyPb) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{1}
}

func (x *BfdmgrGeneralSessionKeyPb) GetType() BfdmgrSessionType {
	if x != nil {
		return x.Type
	}
	return BfdmgrSessionType_SESSION_TYPE_UNKNOWN
}

func (m *BfdmgrGeneralSessionKeyPb) GetKey() isBfdmgrGeneralSessionKeyPb_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (x *BfdmgrGeneralSessionKeyPb) GetP2P() *BfdmgrGeneralSessionKeyPb_P2PKey {
	if x, ok := x.GetKey().(*BfdmgrGeneralSessionKeyPb_P2P); ok {
		return x.P2P
	}
	return nil
}

func (x *BfdmgrGeneralSessionKeyPb) GetMicrobfd() *BfdmgrGeneralSessionKeyPb_MicrobfdKey {
	if x, ok := x.GetKey().(*BfdmgrGeneralSessionKeyPb_Microbfd); ok {
		return x.Microbfd
	}
	return nil
}

func (x *BfdmgrGeneralSessionKeyPb) GetSbfdecho() *BfdmgrGeneralSessionKeyPb_SbfdechoKey {
	if x, ok := x.GetKey().(*BfdmgrGeneralSessionKeyPb_Sbfdecho); ok {
		return x.Sbfdecho
	}
	return nil
}

type isBfdmgrGeneralSessionKeyPb_Key interface {
	isBfdmgrGeneralSessionKeyPb_Key()
}

type BfdmgrGeneralSessionKeyPb_P2P struct {
	P2P *BfdmgrGeneralSessionKeyPb_P2PKey `protobuf:"bytes,20,opt,name=p2p,proto3,oneof"`
}

type BfdmgrGeneralSessionKeyPb_Microbfd struct {
	Microbfd *BfdmgrGeneralSessionKeyPb_MicrobfdKey `protobuf:"bytes,30,opt,name=microbfd,proto3,oneof"`
}

type BfdmgrGeneralSessionKeyPb_Sbfdecho struct {
	Sbfdecho *BfdmgrGeneralSessionKeyPb_SbfdechoKey `protobuf:"bytes,40,opt,name=sbfdecho,proto3,oneof"`
}

func (*BfdmgrGeneralSessionKeyPb_P2P) isBfdmgrGeneralSessionKeyPb_Key() {}

func (*BfdmgrGeneralSessionKeyPb_Microbfd) isBfdmgrGeneralSessionKeyPb_Key() {}

func (*BfdmgrGeneralSessionKeyPb_Sbfdecho) isBfdmgrGeneralSessionKeyPb_Key() {}

// *
// Represents BFD session data.
type BfdmgrGeneralSessionDataPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  BfdmgrSessionStatus                             `protobuf:"varint,1,opt,name=status,proto3,enum=srlinux.sdk.BfdmgrSessionStatus" json:"status,omitempty"`                                              // Status of the session
	SubType BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType `protobuf:"varint,2,opt,name=sub_type,json=subType,proto3,enum=srlinux.sdk.BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType" json:"sub_type,omitempty"` // Subtype of the session
	// src_if_id is only populated for P2P type
	SrcIfId uint32 `protobuf:"varint,3,opt,name=src_if_id,json=srcIfId,proto3" json:"src_if_id,omitempty"` // Source interface ID
}

func (x *BfdmgrGeneralSessionDataPb) Reset() {
	*x = BfdmgrGeneralSessionDataPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdmgrGeneralSessionDataPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdmgrGeneralSessionDataPb) ProtoMessage() {}

func (x *BfdmgrGeneralSessionDataPb) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdmgrGeneralSessionDataPb.ProtoReflect.Descriptor instead.
func (*BfdmgrGeneralSessionDataPb) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{2}
}

func (x *BfdmgrGeneralSessionDataPb) GetStatus() BfdmgrSessionStatus {
	if x != nil {
		return x.Status
	}
	return BfdmgrSessionStatus_INVALID
}

func (x *BfdmgrGeneralSessionDataPb) GetSubType() BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType {
	if x != nil {
		return x.SubType
	}
	return BfdmgrGeneralSessionDataPb_SESSION_SUB_TYPE_UNKNOWN
}

func (x *BfdmgrGeneralSessionDataPb) GetSrcIfId() uint32 {
	if x != nil {
		return x.SrcIfId
	}
	return 0
}

// *
// Represents BFD session notification.
type BfdSessionNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   SdkMgrOperation             `protobuf:"varint,1,opt,name=op,proto3,enum=srlinux.sdk.SdkMgrOperation" json:"op,omitempty"` // Operation such as session create, delete, or update
	Key  *BfdmgrGeneralSessionKeyPb  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                 // Session key
	Data *BfdmgrGeneralSessionDataPb `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                               // Session data
}

func (x *BfdSessionNotification) Reset() {
	*x = BfdSessionNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdSessionNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdSessionNotification) ProtoMessage() {}

func (x *BfdSessionNotification) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdSessionNotification.ProtoReflect.Descriptor instead.
func (*BfdSessionNotification) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{3}
}

func (x *BfdSessionNotification) GetOp() SdkMgrOperation {
	if x != nil {
		return x.Op
	}
	return SdkMgrOperation_Create
}

func (x *BfdSessionNotification) GetKey() *BfdmgrGeneralSessionKeyPb {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BfdSessionNotification) GetData() *BfdmgrGeneralSessionDataPb {
	if x != nil {
		return x.Data
	}
	return nil
}

type BfdmgrGeneralSessionKeyPb_P2PKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcIpAddr      *IpAddressPb `protobuf:"bytes,1,opt,name=src_ip_addr,json=srcIpAddr,proto3" json:"src_ip_addr,omitempty"`               // Source IP address of the session
	DstIpAddr      *IpAddressPb `protobuf:"bytes,2,opt,name=dst_ip_addr,json=dstIpAddr,proto3" json:"dst_ip_addr,omitempty"`               // Destination IP address of the session
	InstanceId     uint32       `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`             // Network instance identifier
	Ipv6LlIfId     uint32       `protobuf:"varint,4,opt,name=ipv6_ll_if_id,json=ipv6LlIfId,proto3" json:"ipv6_ll_if_id,omitempty"`         // Global if id for ipv6 link local session, otherwise 0
	SpecifiedDiscr bool         `protobuf:"varint,5,opt,name=specified_discr,json=specifiedDiscr,proto3" json:"specified_discr,omitempty"` // True if discriminators are specified
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) Reset() {
	*x = BfdmgrGeneralSessionKeyPb_P2PKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdmgrGeneralSessionKeyPb_P2PKey) ProtoMessage() {}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdmgrGeneralSessionKeyPb_P2PKey.ProtoReflect.Descriptor instead.
func (*BfdmgrGeneralSessionKeyPb_P2PKey) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) GetSrcIpAddr() *IpAddressPb {
	if x != nil {
		return x.SrcIpAddr
	}
	return nil
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) GetDstIpAddr() *IpAddressPb {
	if x != nil {
		return x.DstIpAddr
	}
	return nil
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) GetInstanceId() uint32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) GetIpv6LlIfId() uint32 {
	if x != nil {
		return x.Ipv6LlIfId
	}
	return 0
}

func (x *BfdmgrGeneralSessionKeyPb_P2PKey) GetSpecifiedDiscr() bool {
	if x != nil {
		return x.SpecifiedDiscr
	}
	return false
}

type BfdmgrGeneralSessionKeyPb_MicrobfdKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
}

func (x *BfdmgrGeneralSessionKeyPb_MicrobfdKey) Reset() {
	*x = BfdmgrGeneralSessionKeyPb_MicrobfdKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdmgrGeneralSessionKeyPb_MicrobfdKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdmgrGeneralSessionKeyPb_MicrobfdKey) ProtoMessage() {}

func (x *BfdmgrGeneralSessionKeyPb_MicrobfdKey) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdmgrGeneralSessionKeyPb_MicrobfdKey.ProtoReflect.Descriptor instead.
func (*BfdmgrGeneralSessionKeyPb_MicrobfdKey) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BfdmgrGeneralSessionKeyPb_MicrobfdKey) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type BfdmgrGeneralSessionKeyPb_SbfdechoKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId            uint32       `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Network instance identifier
	SrPolicySegmentListId uint32       `protobuf:"varint,2,opt,name=sr_policy_segment_list_id,json=srPolicySegmentListId,proto3" json:"sr_policy_segment_list_id,omitempty"`
	SrPolicyColor         uint32       `protobuf:"varint,3,opt,name=sr_policy_color,json=srPolicyColor,proto3" json:"sr_policy_color,omitempty"`
	SrPolicyEndpoint      *IpAddressPb `protobuf:"bytes,4,opt,name=sr_policy_endpoint,json=srPolicyEndpoint,proto3" json:"sr_policy_endpoint,omitempty"`
}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) Reset() {
	*x = BfdmgrGeneralSessionKeyPb_SbfdechoKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ndk_bfd_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdmgrGeneralSessionKeyPb_SbfdechoKey) ProtoMessage() {}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) ProtoReflect() protoreflect.Message {
	mi := &file_ndk_bfd_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdmgrGeneralSessionKeyPb_SbfdechoKey.ProtoReflect.Descriptor instead.
func (*BfdmgrGeneralSessionKeyPb_SbfdechoKey) Descriptor() ([]byte, []int) {
	return file_ndk_bfd_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) GetInstanceId() uint32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) GetSrPolicySegmentListId() uint32 {
	if x != nil {
		return x.SrPolicySegmentListId
	}
	return 0
}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) GetSrPolicyColor() uint32 {
	if x != nil {
		return x.SrPolicyColor
	}
	return 0
}

func (x *BfdmgrGeneralSessionKeyPb_SbfdechoKey) GetSrPolicyEndpoint() *IpAddressPb {
	if x != nil {
		return x.SrPolicyEndpoint
	}
	return nil
}

var File_ndk_bfd_service_proto protoreflect.FileDescriptor

var file_ndk_bfd_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6e, 0x64, 0x6b, 0x2f, 0x62, 0x66, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78,
	0x2e, 0x73, 0x64, 0x6b, 0x1a, 0x14, 0x6e, 0x64, 0x6b, 0x2f, 0x73, 0x64, 0x6b, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x1d, 0x42, 0x66,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x50, 0x62,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xba, 0x06, 0x0a, 0x19, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x50, 0x62, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x03, 0x70, 0x32, 0x70, 0x18, 0x14,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x50, 0x62, 0x2e, 0x50, 0x32, 0x70,
	0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x03, 0x70, 0x32, 0x70, 0x12, 0x50, 0x0a, 0x08, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x62, 0x66, 0x64, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x73,
	0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64, 0x6d, 0x67,
	0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b,
	0x65, 0x79, 0x50, 0x62, 0x2e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x62, 0x66, 0x64, 0x4b, 0x65, 0x79,
	0x48, 0x00, 0x52, 0x08, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x62, 0x66, 0x64, 0x12, 0x50, 0x0a, 0x08,
	0x73, 0x62, 0x66, 0x64, 0x65, 0x63, 0x68, 0x6f, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64,
	0x6d, 0x67, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x50, 0x62, 0x2e, 0x53, 0x62, 0x66, 0x64, 0x65, 0x63, 0x68, 0x6f, 0x4b,
	0x65, 0x79, 0x48, 0x00, 0x52, 0x08, 0x73, 0x62, 0x66, 0x64, 0x65, 0x63, 0x68, 0x6f, 0x1a, 0xe9,
	0x01, 0x0a, 0x06, 0x50, 0x32, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x72, 0x63,
	0x5f, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x49, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x62, 0x52, 0x09, 0x73, 0x72, 0x63, 0x49, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x38, 0x0a, 0x0b, 0x64, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x50, 0x62, 0x52, 0x09, 0x64, 0x73, 0x74, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0d, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6c, 0x6c, 0x5f, 0x69, 0x66, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x70, 0x76, 0x36, 0x4c, 0x6c, 0x49, 0x66, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x64,
	0x69, 0x73, 0x63, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x44, 0x69, 0x73, 0x63, 0x72, 0x1a, 0x34, 0x0a, 0x0b, 0x4d, 0x69,
	0x63, 0x72, 0x6f, 0x62, 0x66, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0xd8, 0x01, 0x0a, 0x0b, 0x53, 0x62, 0x66, 0x64, 0x65, 0x63, 0x68, 0x6f, 0x4b, 0x65, 0x79,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x19, 0x73, 0x72, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x73, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73,
	0x72, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x46, 0x0a, 0x12, 0x73, 0x72, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x49, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x62, 0x52, 0x10, 0x73, 0x72, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x22, 0x82, 0x03, 0x0a, 0x1a, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x62, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x20, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x57, 0x0a, 0x08, 0x73,
	0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e,
	0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64, 0x6d,
	0x67, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x62, 0x2e, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x09, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x66, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x72, 0x63, 0x49, 0x66, 0x49, 0x64,
	0x22, 0xb4, 0x01, 0x0a, 0x14, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x49, 0x4e, 0x47,
	0x4c, 0x45, 0x5f, 0x48, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x55, 0x4c,
	0x54, 0x49, 0x5f, 0x48, 0x4f, 0x50, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x45, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x49, 0x43,
	0x52, 0x4f, 0x42, 0x46, 0x44, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x42, 0x46, 0x44,
	0x5f, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x04, 0x22, 0xbd, 0x01, 0x0a, 0x16, 0x42, 0x66, 0x64, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x53, 0x64, 0x6b,
	0x4d, 0x67, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70,
	0x12, 0x38, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64, 0x6d,
	0x67, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x50, 0x62, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x72, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x42, 0x66, 0x64, 0x6d, 0x67, 0x72, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x62, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x4e, 0x0a, 0x13, 0x42, 0x66, 0x64, 0x6d, 0x67,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41,
	0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x03, 0x12,
	0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x04, 0x2a, 0x7a, 0x0a, 0x11, 0x42, 0x66, 0x64, 0x6d, 0x67,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x32, 0x50, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15,
	0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x49, 0x43,
	0x52, 0x4f, 0x42, 0x46, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x42, 0x46, 0x44, 0x5f, 0x45, 0x43, 0x48,
	0x4f, 0x10, 0x03, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x69, 0x61, 0x2f, 0x73, 0x72, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2d,
	0x6e, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x6e, 0x64, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ndk_bfd_service_proto_rawDescOnce sync.Once
	file_ndk_bfd_service_proto_rawDescData = file_ndk_bfd_service_proto_rawDesc
)

func file_ndk_bfd_service_proto_rawDescGZIP() []byte {
	file_ndk_bfd_service_proto_rawDescOnce.Do(func() {
		file_ndk_bfd_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ndk_bfd_service_proto_rawDescData)
	})
	return file_ndk_bfd_service_proto_rawDescData
}

var file_ndk_bfd_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ndk_bfd_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ndk_bfd_service_proto_goTypes = []interface{}{
	(BfdmgrSessionStatus)(0),                             // 0: srlinux.sdk.BfdmgrSessionStatus
	(BfdmgrSessionType)(0),                               // 1: srlinux.sdk.BfdmgrSessionType
	(BfdmgrGeneralSessionDataPb_BfdmgrSessionSubType)(0), // 2: srlinux.sdk.BfdmgrGeneralSessionDataPb.BfdmgrSessionSubType
	(*BfdSessionSubscriptionRequest)(nil),                // 3: srlinux.sdk.BfdSessionSubscriptionRequest
	(*BfdmgrGeneralSessionKeyPb)(nil),                    // 4: srlinux.sdk.BfdmgrGeneralSessionKeyPb
	(*BfdmgrGeneralSessionDataPb)(nil),                   // 5: srlinux.sdk.BfdmgrGeneralSessionDataPb
	(*BfdSessionNotification)(nil),                       // 6: srlinux.sdk.BfdSessionNotification
	(*BfdmgrGeneralSessionKeyPb_P2PKey)(nil),             // 7: srlinux.sdk.BfdmgrGeneralSessionKeyPb.P2pKey
	(*BfdmgrGeneralSessionKeyPb_MicrobfdKey)(nil),        // 8: srlinux.sdk.BfdmgrGeneralSessionKeyPb.MicrobfdKey
	(*BfdmgrGeneralSessionKeyPb_SbfdechoKey)(nil),        // 9: srlinux.sdk.BfdmgrGeneralSessionKeyPb.SbfdechoKey
	(SdkMgrOperation)(0),                                 // 10: srlinux.sdk.SdkMgrOperation
	(*IpAddressPb)(nil),                                  // 11: srlinux.sdk.IpAddressPb
}
var file_ndk_bfd_service_proto_depIdxs = []int32{
	4,  // 0: srlinux.sdk.BfdSessionSubscriptionRequest.key:type_name -> srlinux.sdk.BfdmgrGeneralSessionKeyPb
	1,  // 1: srlinux.sdk.BfdmgrGeneralSessionKeyPb.type:type_name -> srlinux.sdk.BfdmgrSessionType
	7,  // 2: srlinux.sdk.BfdmgrGeneralSessionKeyPb.p2p:type_name -> srlinux.sdk.BfdmgrGeneralSessionKeyPb.P2pKey
	8,  // 3: srlinux.sdk.BfdmgrGeneralSessionKeyPb.microbfd:type_name -> srlinux.sdk.BfdmgrGeneralSessionKeyPb.MicrobfdKey
	9,  // 4: srlinux.sdk.BfdmgrGeneralSessionKeyPb.sbfdecho:type_name -> srlinux.sdk.BfdmgrGeneralSessionKeyPb.SbfdechoKey
	0,  // 5: srlinux.sdk.BfdmgrGeneralSessionDataPb.status:type_name -> srlinux.sdk.BfdmgrSessionStatus
	2,  // 6: srlinux.sdk.BfdmgrGeneralSessionDataPb.sub_type:type_name -> srlinux.sdk.BfdmgrGeneralSessionDataPb.BfdmgrSessionSubType
	10, // 7: srlinux.sdk.BfdSessionNotification.op:type_name -> srlinux.sdk.SdkMgrOperation
	4,  // 8: srlinux.sdk.BfdSessionNotification.key:type_name -> srlinux.sdk.BfdmgrGeneralSessionKeyPb
	5,  // 9: srlinux.sdk.BfdSessionNotification.data:type_name -> srlinux.sdk.BfdmgrGeneralSessionDataPb
	11, // 10: srlinux.sdk.BfdmgrGeneralSessionKeyPb.P2pKey.src_ip_addr:type_name -> srlinux.sdk.IpAddressPb
	11, // 11: srlinux.sdk.BfdmgrGeneralSessionKeyPb.P2pKey.dst_ip_addr:type_name -> srlinux.sdk.IpAddressPb
	11, // 12: srlinux.sdk.BfdmgrGeneralSessionKeyPb.SbfdechoKey.sr_policy_endpoint:type_name -> srlinux.sdk.IpAddressPb
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ndk_bfd_service_proto_init() }
func file_ndk_bfd_service_proto_init() {
	if File_ndk_bfd_service_proto != nil {
		return
	}
	file_ndk_sdk_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ndk_bfd_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdSessionSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_bfd_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdmgrGeneralSessionKeyPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_bfd_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdmgrGeneralSessionDataPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_bfd_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdSessionNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_bfd_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdmgrGeneralSessionKeyPb_P2PKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_bfd_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdmgrGeneralSessionKeyPb_MicrobfdKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ndk_bfd_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfdmgrGeneralSessionKeyPb_SbfdechoKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ndk_bfd_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*BfdmgrGeneralSessionKeyPb_P2P)(nil),
		(*BfdmgrGeneralSessionKeyPb_Microbfd)(nil),
		(*BfdmgrGeneralSessionKeyPb_Sbfdecho)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ndk_bfd_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ndk_bfd_service_proto_goTypes,
		DependencyIndexes: file_ndk_bfd_service_proto_depIdxs,
		EnumInfos:         file_ndk_bfd_service_proto_enumTypes,
		MessageInfos:      file_ndk_bfd_service_proto_msgTypes,
	}.Build()
	File_ndk_bfd_service_proto = out.File
	file_ndk_bfd_service_proto_rawDesc = nil
	file_ndk_bfd_service_proto_goTypes = nil
	file_ndk_bfd_service_proto_depIdxs = nil
}
